#!/usr/bin/env python3
"""Generate the GUI's embedded capability-document snapshot.

Scans `docs/capabilities/*/{en-US,zh-CN}.md` and writes
`apps/linxira-bio-ui/src/docs_snapshot.rs`, a match over `(capability, locale)`
returning the document text via `include_str!`. The committed snapshot is the
offline fallback used when runtime documentation is unavailable; regenerate it
whenever capability docs change:

    python3 scripts/embed-docs-snapshot.py

`scripts/validate-repository.py` fails the build when the committed snapshot is
stale.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs" / "capabilities"
OUTPUT = ROOT / "apps" / "linxira-bio-ui" / "src" / "docs_snapshot.rs"

LOCALES = ("en-US", "zh-CN")


def render_snapshot() -> str:
    entries: list[tuple[str, str, Path]] = []
    if not DOCS.is_dir():
        raise SystemExit(f"capability docs directory not found: {DOCS}")
    for capability_dir in sorted(DOCS.iterdir()):
        if not capability_dir.is_dir():
            continue
        capability = capability_dir.name
        for locale in LOCALES:
            document = capability_dir / f"{locale}.md"
            if document.is_file():
                entries.append((capability, locale, document))
    if not entries:
        raise SystemExit("no capability documents found")

    lines = [
        "// Generated by scripts/embed-docs-snapshot.py - do not edit.",
        "// Offline fallback capability documentation for the desktop GUI.",
        "",
        "pub fn embedded_document(capability: &str, locale: &str) -> Option<&'static str> {",
        "    match (capability, locale) {",
    ]
    for capability, locale, document in entries:
        relative = document.relative_to(ROOT).as_posix()
        lines.append(
            f'        ("{capability}", "{locale}") => Some(include_str!("../../../{relative}")),'
        )
    lines.extend(
        [
            "        _ => None,",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed snapshot is current without writing",
    )
    args = parser.parse_args()

    rendered = render_snapshot()
    if args.check:
        committed = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if committed != rendered:
            print(
                f"stale embedded docs snapshot: {OUTPUT.relative_to(ROOT)} "
                "is out of date; run scripts/embed-docs-snapshot.py",
                file=sys.stderr,
            )
            return 1
        print(f"embedded docs snapshot is current ({len(OUTPUT.read_text(encoding='utf-8'))} bytes)")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} with {len(rendered)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
